function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-May-2024 20:05:32

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'ZMinorGrid','on','YMinorGrid','on',...
    'XMinorGrid','on');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[0 0 1],'DisplayName','Base case');
set(plot1(2),'DisplayName','With DNR only','Color',[0 0 0]);
set(plot1(3),'Color',[1 0 0],'DisplayName','With DNR and DG');

% Create xlabel
xlabel('Buses');

% Create ylabel
ylabel('Vbus(pu)');

% Create title
title('Bus voltage profile Comparison');

% Create legend
legend(axes1,'show');

